//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oefenExamen12_13
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trein
    {
        public string Kentekennr { get; set; }
        public string Bestemming { get; set; }
        public Nullable<int> Spoor { get; set; }
        public Nullable<System.DateTime> Vertrek { get; set; }
        public Nullable<int> AantalPassagiers { get; set; }
        public Nullable<int> MaxAantalPassagiers { get; set; }
    }
}
